theme: jekyll-theme-minimal

title: Yuma Mizuyabu
description: >
  Software Engineer based in the UK.<br>
  <a href="https://www.linkedin.com/in/yuma_mizuyabu" target="_blank">LinkedIn</a>
show_downloads: false

github_username: Nolit

markdown: kramdown
lang: en
timezone: Europe/London
